### ISSUE TITLE
Calling the send card results in request timed out

### ISSUE THREAD

**Issue by danandonibjss** [UnifiedPaymentSolutions/everypay-ios#1]
Every other request from the app works perfectly and confirms presence of internet connection. The only request which fails after a long period of awaiting is everypay's send card method [the test base url].

Please assist with this issue. The parameters sent are fully completed and validated, just that there is absolutely no response for the test URL

**Comment by danandonibjss** [comment]
After debugging the issue it proved that the URL specified inside the SDK was an invalid one.

**Comment by reneneimann** [comment]
@danandonibjss Thank you for pointing this out! It will be fixed in the SDK this week.
